# Generated by Django 4.1.6 on 2023-02-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
